### ISSUE TITLE
Add in-/decrement button entities for speed

### ISSUE THREAD

**Issue by webmediart-github** [indiefan/king_smith#49]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hi, the remote allows to increment the speed by a set step-value. It would be handy for UI and automation purposes, to have these also as entities for given devices.

### Describe the solution you'd like

- add number entity for in-/decrement step (default 0.5)
- add button entity to increment current walking speed by defined step-size (e.g. 0.5)
- add button entity to decrement current walking speed by defined step-size (e.g. 0.5)

### Describe alternatives you've considered
Action calls number.increment and respective number.decrement (provided by Spooky HACS-integration) did fail.
But I did have success with number.set_value eventually:
```
action: number.set_value
target:
  entity_id: number.walkingpad_speed
data_template:
  value: "{{ states('number.walkingpad_speed') | float + 0.5 }}"
```
However, as templating is only possible with data_template and some(/all?) UI elements expect "data", this is not working for UI

**Comment by tenaran** [comment]
firstly - thank you to everyone who has already contributed - this is way beyond me at the moment, but I've been able to add the integration and it's found my C1 instantly. Amazing. 

I "think" I've hit the same problem as @webmediart-github  - I've tried to create a script to change the speed so I can have an interval training program. Trying to use a field value to set the speed throws this error: `Message malformed: expected float for dictionary value @ data['value']`  (script below in case it's just be not knowing what I'm doing yet?) 

Is it that you can't use a template to set the value like this, and an action is required? I'm so sorry if this is unrelated

```
sequence:
  - type: turn_on
    device_id: xxxx
    entity_id: xxxx
    domain: switch
  - repeat:
      count: "{{ float(number_of_reps) }}"
      sequence:
        - device_id: xxxx
          domain: number
          entity_id: xxxx
          type: set_value
          value: "{{ slow_speed }}"
        - delay: "{{ duration_of_intervals }}"
        - device_id: xxxx
          domain: number
          entity_id: xxxx
          type: set_value
          value: "{{ fast_speed }}"
        - delay: "{{ duration_of_intervals }}"
  - type: turn_off
    device_id: xxxx
    entity_id: xxxx
    domain: switch
alias: "Walking Pad interval training "
description: ""
fields:
  slow_speed:
    selector:
      number:
        min: 0.5
        max: 6
        step: 0.5
    name: "Slow Speed "
    required: true
    default: 2
  fast_speed:
    selector:
      number:
        min: 0.5
        max: 6
        step: 0.5
    name: "Fast Speed "
    default: 5
    required: true
  number_of_reps:
    selector:
      number:
        min: 1
        max: 10
        step: 1
    name: "Number of reps "
    required: true
    default: 3
  duration_of_intervals:
    selector:
      time: {}
    name: "Duration of Intervals "
    default: "00:03:00"
    required: true
```

**Comment by webmediart-github** [comment]
This is the action I use to set the speed. 
```
action: number.set_value
target:
  entity_id: number.walkingpad_speed
data_template:
  value: "{{ states('input_number.current_walkingpad_speed') }}"
```

However, as the device's speed is reported slow, I am using a helper input_number (current_walkingpad_speed as seen above) for manipulation of the speed like this (increasing in this case)
```
action: input_number.increment
target:
  entity_id:
    - input_number.current_walkingpad_speed
data_template:
  amount: 0.5
```


Hope it helps.
